spring:
    profiles: dev
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/inaya2
        username: root
        password: "freedom"
        pooled: true
    jpa:
        generate-dll: true

name: test-YAML
envinronment: test
servers:
    - www.abc.test.com
    - www.cba.com

hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---

spring:
    profiles: test
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/inaya2Test
        username: root
        password: "freedom"
        pooled: true
    jpa:
        generate-dll: true

name: test-YAML
envinronment: test
servers:
    - www.abc.test.com
    - www.cba.com

hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---

spring:
     profiles: prod
     datasource:
         driverClassName: com.mysql.jdbc.Driver
         url:   jdbc:mysql://127.0.0.1:3306/inaya2
         username: root
         password: "freedom"
         pooled: true
     jpa:
         generate-dll: true

name: prod-YAML
envinronment: prod
servers:
    - www.abc.test.com
    - www.cba.com

hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

